[build]
  functions = "functions"

[[redirects]]
  from = "/redirect"
  to = "https://7125-2a02-1811-3503-8b00-9c93-9da1-22a0-1fc4.ngrok-free.app/actions/cloudinary/notifications/process?volume=1"
  status = 200
  force = true
  headers = {ngrok-skip-browser-warning = "6024"}

